### ISSUE TITLE
[기능] 커뮤니티

### ISSUE THREAD

**Issue by songhye0u0** [choehyeonjin/OSS-YYJ-group5#17]
# 구현 내용
### 커뮤니티
- [x] 캘린더 위쪽 구단 누르면 구단 별 커뮤니티 창으로 이동
- [x] 커뮤니티 창 - 최신 5개 Q&A 및 다이어리를 볼 수 있음
- [x] 구단 별 설명, 먹거리, 우승 년도를 볼 수 있음
- [x] 각 구단의 응원가 및 하이라이트를 볼 수 있음
- [x] 각 구단별 유튜브, 홈페이지 이동 가능

### Q&A
- [x] 구단별 Q&A를 작성하고 볼 수 있음
- [x] 답글 기능

### 다이어리
- [x] 구단 별 다이어리 창 구현

**Comment by choehyeonjin** [comment]
Q&A 창 한글로 바꿔주세요.

**Comment by jangsh7** [comment]
각 팀 커뮤니티 중 몇몇 팀의 로고가 잘려있는 것 같습니다.
