### ISSUE TITLE
프로젝트 역할

### ISSUE THREAD

**Issue by choehyeonjin** [choehyeonjin/OSS-YYJ-group5#8]
현진
- KBO 웹 스크래핑 (프리시즌, 정규시즌, 포스트시즌 경기 날짜/시간/결과/구장/우천취소여부) 
- 캘린더 페이지에서 날짜 클릭시 경기 선택
- 일기 작성 페이지에 해당 날짜 경기 데이터 출력
- 일기 작성시 경기 결과 선택 (승, 패, 무)
- 아이디 찾기 기능 구현
- 비밀번호 찾기 기능 구현

**Comment by jangsh7** [comment]
서현
- 구단별 로고 및 캘린더 이미지 제작하기
- 요야정 로고 제작하기
- 프로젝트 제목 작성하기
- 프로젝트 주제 요약 글 작성하기
- 구단별 캘린더 이미지 변경 구현하기
- 캘린더에 사진 넣을 수 있는 기능 구현하기

**Comment by songhye0u0** [comment]
송혜

- 로그인 창 디자인 및 구현
- 회원 가입 창 디자인 및 구현
- 아이디 찾기 창 디자인 및 구현
- 비밀번호 찾기 창 디자인 및 구현
- 로그인 후 넘어가는 메인 캘린더 창 디자인 및 구현
- 직관 일기 작성하는 창 디자인 및 구현
- 구장 별 팬들이 쓴 일기를 볼 수 있는 창 디자인 및 구현
